apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ingest-image
spec:
  template:
    spec:
      containers:
        - image: qhzd4479/ingest-image:v1
          ports:
            - containerPort: 8080