apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transform-image
spec:
  template:
    spec:
      containers:
        - image: qhzd4479/transform-image:v1
          ports:
             - containerPort: 8080